version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mu-documentation
    container_name: mu-documentation
    ports:
      - "81:81"
    volumes:
      - ./:/var/www
    networks:
      - app-network

#Redes
networks:
  app-network:
    driver: bridge
