version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mu-documentation
    ports:
      - "3123:3123"
    volumes:
      - ./:/var/www
    networks:
      - app-network

#Redes
networks:
  app-network:
    driver: bridge
